### ISSUE TITLE
Cannot synchronize wallet to mainnet (Mac)

### ISSUE THREAD

**Issue by YCC25** [nervosnetwork/neuron#2546]
### Detail of the issue

- Apple iMac (OS 10.13.6) 
- Neuron Wallet (v0.103.2)
- Cache cleared multiple times

Hello. 
I have downloaded and installed the latest Neuron Wallet (v0.103.2), but it simply refuses to connect to Mainnet default node.
I always get "Block Synced 0% 0/0" even after 3 hours.
I have tried with my VPN on.
I have tried with my VPN off
I get the same sync issue

Network is pointing to : 'http://localhost:8114'
Is that correct ? 

If anyone could help that would be great.
Fantastic project.

Cheers

### bundled-ckb.log

```shell
File not found
```

### main.log

```shell
[2022-12-14 10:11:43.457] [info] CKB:	process closed
[2022-12-14 10:11:46.243] [info] Indexer:	start: PORT: 8118...
[2022-12-14 10:11:46.244] [warn] function call error: Error: Port is not reachable, retry 2 ...
[2022-12-14 10:11:47.248] [warn] function call error: Error: Port is not reachable, retry 3 ...
[2022-12-14 10:11:48.253] [warn] function call error: Error: Port is not reachable, retry 4 ...
[2022-12-14 10:11:49.259] [warn] function call error: Error: Port is not reachable, retry 5 ...
[2022-12-14 10:11:53.232] [info] Monitor: is restarting ckb-indexer process
[2022-12-14 10:11:53.233] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2022-12-14 10:11:53.338] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2022-12-14 10:11:53.445] [info] Monitor: is restarting ckb process
[2022-12-14 10:11:53.445] [info] CKB:	Initializing node...
[2022-12-14 10:11:53.519] [error] CKB:	init fail: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Neuron.app/Contents/bin/ckb (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Neuron.app/Contents/bin/ckb (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib


[2022-12-14 10:11:53.520] [info] CKB:	starting node...
[2022-12-14 10:11:53.522] [info] Monitor: Restarting ckb process success
[2022-12-14 10:11:53.530] [error] CKB:	run fail: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Neuron.app/Contents/bin/ckb (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Neuron.app/Contents/bin/ckb (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by Keith-CY** [comment]
Hi @YCC25 
Neuron@v0.103.2 works with CKB@v0.103.0, and CKB@v0.103.0 requires macOS 10.15 or above. From the report, I found the platform is OS 10.13.6, which is incompatible with CKB Node, so it didn't start.

![image](https://user-images.githubusercontent.com/7271329/207567284-457ec271-1a44-4037-926c-7117d4829575.png)


Ref: 
Specified CKB Version: https://github.com/nervosnetwork/neuron/blob/v0.103.2/.ckb-version#L1
CKB Node Requirement: https://github.com/nervosnetwork/ckb/releases/tag/v0.103.0
